steps:
  - name: python:3.10.10-alpine
    entrypoint: python
    args:
      - "--version"
  # Install dependencies
  - name: python:3.10.10-alpine
    entrypoint: pip
    args:
      - "install"
      - "-r"
      - "requirements.txt"
      - "--user"
  - name: python
    entrypoint: python
    args:
      - "-m"
      - "pytest"
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--memory=$_GCR_MEMORY"
      - "--quiet"
      - "--env-vars-file=.env.yaml"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: sign-game-server
  _TRIGGER_ID: a7bde02b-3e9c-47ac-86e1-2c59d7e904bf
  _DEPLOY_REGION: us-central1
  _GCR_MEMORY: 2Gi
  _GCR_HOSTNAME: us.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - sign-game-server
